// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOBR_lsa7FXhDU8HW-ZvvDQRSLPGXwdxg',
    appId: '1:909749972047:android:44a774aac1462a06edce3a',
    messagingSenderId: '909749972047',
    projectId: 'todo-with-riverpod',
    storageBucket: 'todo-with-riverpod.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApGVhmz_Z020tBvu3Ppi9QyDOAZIAbtgg',
    appId: '1:909749972047:ios:8d074d0adeb6df82edce3a',
    messagingSenderId: '909749972047',
    projectId: 'todo-with-riverpod',
    storageBucket: 'todo-with-riverpod.appspot.com',
    androidClientId: '909749972047-o030l9qt5b9si1qgvet8ct3e5l6oidpe.apps.googleusercontent.com',
    iosClientId: '909749972047-qe35hu9osht7v28j552qaekm0j2i5u87.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoWithRiverpod',
  );
}
